name: Deploy Build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM Install
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    - name: Pin to IPFS
      id: upload
      uses: anantaramdas/ipfs-pinata-deploy-action@39bbda1ce1fe24c69c6f57861b8038278d53688d
      with:
        pin-name: App Site
        path: './build'
        pinata-api-key: ${{ secrets.PINATA_API_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}